CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE vision_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    name VARCHAR(160) NOT NULL,
    description VARCHAR(2000),
    priority VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_vision_areas_user_code UNIQUE (user_id, code)
);

CREATE TABLE dreams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    vision_area_id BIGINT NOT NULL REFERENCES vision_areas(id),
    title VARCHAR(220) NOT NULL,
    description VARCHAR(3000),
    why_important VARCHAR(3000),
    success_definition VARCHAR(3000),
    dream_type VARCHAR(40) NOT NULL,
    priority VARCHAR(40) NOT NULL,
    target_date DATE,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_dreams_user_code UNIQUE (user_id, code)
);

CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    dream_id BIGINT NOT NULL REFERENCES dreams(id),
    title VARCHAR(220) NOT NULL,
    description VARCHAR(3000),
    success_criteria VARCHAR(3000),
    priority VARCHAR(40) NOT NULL,
    target_date DATE,
    status VARCHAR(40) NOT NULL,
    progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
    manual_progress_override BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_goals_user_code UNIQUE (user_id, code)
);

CREATE TABLE vision_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    goal_id BIGINT NOT NULL REFERENCES goals(id),
    title VARCHAR(220) NOT NULL,
    description VARCHAR(3000),
    sequence_number INTEGER NOT NULL,
    is_complex BOOLEAN NOT NULL DEFAULT FALSE,
    priority VARCHAR(40) NOT NULL,
    target_date DATE,
    status VARCHAR(40) NOT NULL,
    progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
    manual_progress_override BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_vision_steps_user_code UNIQUE (user_id, code)
);

CREATE TABLE task_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    step_id BIGINT NOT NULL REFERENCES vision_steps(id),
    title VARCHAR(220) NOT NULL,
    description VARCHAR(3000),
    owner VARCHAR(160) NOT NULL,
    priority VARCHAR(40) NOT NULL,
    start_date DATE,
    due_date DATE NOT NULL,
    status VARCHAR(40) NOT NULL,
    progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
    estimated_hours NUMERIC(8, 2),
    actual_hours NUMERIC(8, 2),
    blocker_reason VARCHAR(2000),
    next_action VARCHAR(2000),
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_task_items_user_code UNIQUE (user_id, code)
);

CREATE TABLE partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    name VARCHAR(180) NOT NULL,
    role VARCHAR(120),
    organization VARCHAR(180),
    email VARCHAR(180),
    phone VARCHAR(60),
    strength VARCHAR(120),
    support_type VARCHAR(40) NOT NULL,
    related_vision_area_id BIGINT REFERENCES vision_areas(id),
    related_dream_id BIGINT REFERENCES dreams(id),
    related_goal_id BIGINT REFERENCES goals(id),
    related_step_id BIGINT REFERENCES vision_steps(id),
    related_task_id BIGINT REFERENCES task_items(id),
    status VARCHAR(40) NOT NULL,
    notes VARCHAR(3000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_partners_user_code UNIQUE (user_id, code)
);

CREATE TABLE communication_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    partner_id BIGINT REFERENCES partners(id),
    related_dream_id BIGINT REFERENCES dreams(id),
    related_goal_id BIGINT REFERENCES goals(id),
    related_task_id BIGINT REFERENCES task_items(id),
    audience VARCHAR(180),
    purpose VARCHAR(500),
    subject VARCHAR(220),
    hook VARCHAR(1000),
    problem VARCHAR(2000),
    request VARCHAR(2000),
    benefit_to_partner VARCHAR(2000),
    expected_outcome VARCHAR(2000),
    message_body VARCHAR(6000),
    status VARCHAR(40) NOT NULL,
    follow_up_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    review_type VARCHAR(40) NOT NULL,
    review_date DATE NOT NULL,
    related_vision_area_id BIGINT REFERENCES vision_areas(id),
    related_dream_id BIGINT REFERENCES dreams(id),
    summary VARCHAR(3000),
    completed_tasks VARCHAR(3000),
    delayed_tasks VARCHAR(3000),
    blocked_tasks VARCHAR(3000),
    lessons_learned VARCHAR(3000),
    next_actions VARCHAR(3000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE obstacles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    related_dream_id BIGINT REFERENCES dreams(id),
    related_goal_id BIGINT REFERENCES goals(id),
    related_step_id BIGINT REFERENCES vision_steps(id),
    related_task_id BIGINT REFERENCES task_items(id),
    title VARCHAR(220) NOT NULL,
    description VARCHAR(3000),
    obstacle_type VARCHAR(40) NOT NULL,
    severity VARCHAR(40) NOT NULL,
    solution VARCHAR(3000),
    required_partner_id BIGINT REFERENCES partners(id),
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE progress_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    related_task_id BIGINT NOT NULL REFERENCES task_items(id),
    progress_percent_before NUMERIC(5, 2) NOT NULL,
    progress_percent_after NUMERIC(5, 2) NOT NULL,
    note VARCHAR(2000),
    logged_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_vision_areas_user_id ON vision_areas(user_id);
CREATE INDEX idx_dreams_user_id ON dreams(user_id);
CREATE INDEX idx_dreams_vision_area_id ON dreams(vision_area_id);
CREATE INDEX idx_goals_user_id ON goals(user_id);
CREATE INDEX idx_goals_dream_id ON goals(dream_id);
CREATE INDEX idx_vision_steps_user_id ON vision_steps(user_id);
CREATE INDEX idx_vision_steps_goal_id ON vision_steps(goal_id);
CREATE INDEX idx_task_items_user_id ON task_items(user_id);
CREATE INDEX idx_task_items_step_id ON task_items(step_id);
CREATE INDEX idx_partners_user_id ON partners(user_id);
CREATE INDEX idx_communication_messages_user_id ON communication_messages(user_id);
CREATE INDEX idx_reviews_user_id ON reviews(user_id);
CREATE INDEX idx_obstacles_user_id ON obstacles(user_id);
CREATE INDEX idx_progress_logs_user_id ON progress_logs(user_id);
