ALTER TABLE vision_areas ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE dreams ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE vision_steps ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE task_items ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE partners ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE obstacles ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE communication_messages ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
