-- FR-15: Partner Recruitment Portal.
--
-- ideal_partner_profiles: the partner a complex step needs, written down before
-- anyone is recruited — required experience, character traits, what would
-- motivate them, and what the user can offer in return. One profile per step
-- (BR-13: it belongs to exactly one step and is archived with it).
CREATE TABLE ideal_partner_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    step_id BIGINT NOT NULL REFERENCES vision_steps(id),
    required_experience VARCHAR(2000),
    character_traits VARCHAR(2000),
    motivation VARCHAR(2000),
    offer_in_return VARCHAR(2000),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_ideal_partner_profiles_step UNIQUE (step_id)
);

-- FR-15.2: the exchange basis a partner responds to.
ALTER TABLE partners ADD COLUMN offer_type VARCHAR(40);
